services:
  portal-frontend:
    image: portal-frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BASE_URL=${VITE_BASE_URL}
        - VITE_BASE44_APP_ID=${VITE_BASE44_APP_ID}
        - VITE_BASE44_APP_BASE_URL=${VITE_BASE44_APP_BASE_URL}
    container_name: frontend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    external: true
